export const siteConfig = {
  name: "Ciel & Stone",
  description:
    "Luxury residential design-build and preconstruction studio for homeowners planning serious kitchens, pools, additions, and whole-home projects across Los Angeles and the Pacific Northwest.",
  url: "https://cielandstone.com",
  // Dynamic OG image generated by app/opengraph-image.tsx
  ogImage: "/opengraph-image.png",
  locale: "en_US",
};
